server {
	listen 127.0.0.1:8080;
	root   www;
	index  index.html;

	client_max_body_size 10485760; # 10MB

	location /uploads {
		upload_store www/uploads;
		methods GET POST;
	}

	location /cgi {
		cgi_pass .py /usr/bin/python;
	}
}
