server {
	listen 127.0.0.1:8080;
	root www;
	index index.html;
	
	location /redirect {
		return 302 /index.html;
	}
	
	location /permanent {
		return 301 /index.html;
	}
}

server {
	listen 127.0.0.1:8081;
	root www;
	index index.html;
	
	location /redirect {
		return 302 /index.html;
	}
}
